### ISSUE TITLE
Add Functionality: PDF Where?!🤔

### ISSUE THREAD

**Issue by adarshxs** [ACM-VIT/PDFMaker#3]
Heya!

How about a nice pdf generator? We will be using fpdf, A popular library for PDF document generation using python.

I would be really cool to see a pdf generated and being able to download the same using a simple button.

Hint: We are already taking user input in the forms field. Why not use that to create the Heading page?

**Comment by avi-dey** [comment]
You want to add download functionality, right?

**Comment by adarshxs** [comment]
I want a function to be implemented in the main app.py script itself that takes in whatever the user inputs, generate a pdf and pass it off to be downloaded using a button

**Comment by avi-dey** [comment]
okay, I can do this.

**Comment by adarshxs** [comment]
@avi-dey Assigned it to you! 

pro-tip: Make sure your code is clear and add necessary comments as this will be the core function that will be updated a lot as the project progresses. Thank you!

**Comment by abhi-shek-09** [comment]
Hey there,
I've got a PR in the queue that tackles those PDF generation and download issues.
Thank you!
